// Runtime configuration for the app. Generated by scripts/set-backend-ip.js
// If this file is wrong, edit it manually.
// Note: For Android emulator use `http://10.0.2.2:4000` to reach the host machine.
// For iOS simulator use `http://localhost:4000`. For a physical device, set
// this to your machine's LAN IP (e.g. http://192.168.x.y:4000) and ensure
// your firewall allows incoming connections on that port.
export const BACKEND_URL = 'http://192.168.134.7:4000';
